# Generated by Django 4.0.5 on 2022-08-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_patientsinfo_patientdob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsinfo',
            name='patientImage',
            field=models.ImageField(upload_to='E:\\TA course\\CSE347\\lab3\\aroggo_lipi\\static/patientsUploadedImage'),
        ),
    ]
